services:
  my-tests:
    build: .

    container_name: my-tests

    working_dir: /app

    volumes:
      - .:/app
      - ./reports:/app/reports

    environment:
      BASE_URL: "http://app:8080"
      PYTHONUNBUFFERED: 1

    depends_on:
      - app

    # лучше фиксировать сеть явно (CI стабильнее)
    networks:
      - test-net

    user: root

    command: ["bash", "./run_tests.sh"]


  app:
    image: your-app-image:latest
    container_name: my-app

    ports:
      - "8080:8080"

    restart: unless-stopped

    networks:
      - test-net

    command: ["bash", "-c", "npm start"]


networks:
  test-net:
    driver: bridge