services:
  tests:
    build:
      context: .
      network: host

    container_name: my-tests

    volumes:
      - ./reports:/app/reports

    network_mode: host

    environment:
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
      - SITE_URL=${SITE_URL}
      - YANDEX_API_KEY=${YANDEX_API_KEY}
      - YANDEX_FOLDER_ID=${YANDEX_FOLDER_ID}