services:
  tests:
    build:
      context: .
      network: host

    volumes:
      - ./reports:/app/reports

    network_mode: host

    environment:
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

    dns:
      - 8.8.8.8
      - 1.1.1.1