#!/bin/bash
set -e

# ===============================
# run_tests.sh
# Script for running tests with Allure and trends support
# ===============================

# Check if Allure is installed
if ! command -v allure &> /dev/null; then
    echo "Error: Allure is not installed or not in PATH"
    exit 1
fi

echo "📁 Preparing folders..."

# 1. Clean old results
rm -rf reports/allure-results
mkdir -p reports/allure-results

# Ensure history dir exists
mkdir -p reports/allure-history

# 2. 🔥 CRITICAL: Copy history INTO allure-results BEFORE tests
if [ -d "reports/allure-history" ] && [ "$(ls -A reports/allure-history 2>/dev/null)" ]; then
    echo "📥 Found previous history, copying into allure-results..."
    mkdir -p reports/allure-results/history
    cp -r reports/allure-history/* reports/allure-results/history/
    echo "✅ History copied ($(ls -1 reports/allure-history | wc -l) files)"
else
    echo "ℹ️ No previous history found (first run)"
fi

echo ""
echo "📁 Contents of allure-results BEFORE tests:"
ls -la reports/allure-results || true

# 3. Run tests
echo ""
echo "🚀 Running tests..."
python -m pytest tests/ --alluredir=reports/allure-results

# 4. Generate Allure report
echo ""
echo "📊 Generating Allure report..."
allure generate reports/allure-results -o reports/allure-report --clean

# 5. Save history for next run
echo ""
echo "💾 Saving history for next run..."

rm -rf reports/allure-history
mkdir -p reports/allure-history

if [ -d "reports/allure-report/history" ] && [ "$(ls -A reports/allure-report/history 2>/dev/null)" ]; then
    cp -r reports/allure-report/history/* reports/allure-history/
    echo "✅ History saved ($(ls -1 reports/allure-history | wc -l) files)"
else
    echo "⚠️ No history generated by Allure!"
fi

echo ""
echo "📁 Final history contents:"
ls -la reports/allure-history || true

echo ""
echo "🎉 Done! Allure report generated"
echo "👉 If this was the first run, trends will appear on the next run"