name: Playwright CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: self-hosted

    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Checkout gh-pages (history)
      - name: Checkout gh-pages branch (history)
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
        continue-on-error: true

      # 3. Load history
      - name: Load previous Allure history
        run: |
          mkdir -p reports/allure-history

          if [ -d "gh-pages/history" ]; then
            cp -r gh-pages/history/* reports/allure-history/ || true
          fi

      # 4. Stop old containers
      - name: Stop old containers
        run: docker compose down || true

      # 5. Run tests (ВАЖНО)
      - name: Build and run tests
        run: docker compose up --build --abort-on-container-exit --exit-code-from tests

      # 6. Save history
      - name: Save new history
        if: always()
        run: |
          mkdir -p history

          if [ -d "reports/allure-report/history" ]; then
            cp -r reports/allure-report/history/* history/
          fi

      # 7. Upload report artifact
      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: reports/allure-report/

  deploy:
    needs: test
    runs-on: self-hosted
    if: always()   # ← КЛЮЧЕВОЕ

    steps:
      # 1. Download report
      - name: Download Allure report
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      # 2. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy Allure report ${{ github.sha }}'

  notify:
    needs: test
    runs-on: self-hosted
    if: failure()

    steps:
      - name: Send email on failure
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "❌ Tests FAILED - ${{ github.repository }}"
          to: ${{ secrets.EMAIL_USERNAME }}
          from: GitHub Actions
          body: |
            Tests failed!

            Repo: ${{ github.repository }}
            Branch: ${{ github.ref }}
            Commit: ${{ github.sha }}

            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}