name: Playwright CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop old containers
        run: docker compose down || true

      # 🔥 создаём папки на хосте (важно для volume)
      - name: Prepare reports folders
        run: mkdir -p reports/allure-results reports/allure-report

      # 🔥 запускаем тесты и явно пишем Allure results в /app/reports
      - name: Run tests
        run: docker compose run --rm tests pytest tests --alluredir=/app/reports/allure-results

      # 🔥 генерируем отчёт из результатов
      - name: Generate Allure report
        run: docker compose run --rm tests allure generate /app/reports/allure-results -o /app/reports/allure-report --clean

      # 🔥 проверка что файлы реально создались
      - name: Debug reports
        run: ls -R reports || true

      # 🔥 загрузка артефакта
      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: reports/allure-report/

  deploy:
    needs: test
    runs-on: self-hosted
    if: success()

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report